### ISSUE TITLE
AWSIdentityManager crashes when using Google OAuth on app resume

### ISSUE THREAD

**Issue by digitalpho3nix** [aws/aws-mobilehub-helper-ios#11]
I am implementing Google OAuth into my AWS powered app using the Mobile Hub system.

I have it set up such that I can successfully log in and authenticate users on the first run of the app, however after killing the process and relaunching the app the whole app instantly crashes with an EXC_BAD_ACCESS before drawing anything on this method:

AWSMobileClient.m

if (!_initialized) {
        [[AWSIdentityManager defaultIdentityManager] resumeSessionWithCompletionHandler:^(id result, NSError *error) {
            NSLog(@"result = %@, error = %@", result, error);
        }];
        _initialized = YES;
    }
Based on my research this seems to be related to Google silent authentication?

My login code for reference; this is copied from this AWS tutorial on their docs:
- (void)handleLoginWithSignInProvider:(id<AWSSignInProvider>)signInProvider {
  [[AWSIdentityManager defaultIdentityManager] loginWithSignInProvider:signInProvider completionHandler:^(id result, NSError *error) {
       if (error) {
           NSLog(@"Login in with SignIn Provider has failed: %@", error);
           [self showLoginError];
           return;
       }
       NSLog(@"Google Login ok!");
   }];
  }
- (void)handleGoogleLogin {
  // Google login scopes can be optionally set, but must be set before user authenticates.
  [[AWSGoogleSignInProvider sharedInstance] setScopes:@[@"openid"]];
  
  // Sets up the view controller that the Google signin will be launched from.
  [[AWSGoogleSignInProvider sharedInstance] setViewControllerForGoogleSignIn:self];
  [self handleLoginWithSignInProvider:[AWSGoogleSignInProvider sharedInstance]];
  }

**Comment by BruceBuckland** [comment]
Possible cause:  AWSMobile client has a bug (or missing feature) with respect to the resumption of existing sessions.  If you (in your viewDidLoad for example) try to use an identityId upon startup you will get a crash.  That is because AWSIdentityManager defaultIdentityManager] resumeSessionWithCompletionHandler takes a while to finish resuming the sessions (it has to hit an AWS service through the web) but it returns immediately with true (or YES for Obj-c) and the appDelegate kicks off the ViewController.

What I did was to modify AWSMobileClient.swift to do the following:

`        if (!isInitialized) {
            AWSIdentityManager.defaultIdentityManager().resumeSessionWithCompletionHandler({(result: AnyObject?, error: NSError?) -> Void in
                print("Result: \(result) \n Error:\(error)")
                NSNotificationCenter.defaultCenter().postNotificationName(AWSMobileClient.AWSMobileClientDidCompleteInitialization, object: self, userInfo: nil)
            })
            isInitialized = true
        }`

and then defined that notification just after the class

`  // Constants 
    static let AWSMobileClientDidCompleteInitialization = "com.amazonaws.AWSMobileClient.AWSMobileClientDidCompleteInitialization"`

then in your viewController (or somewhere else) set up a target for the notification. I did the following in my MainViewController.swift 

`// when we really have an identityId - start processing.
        completeInitializationObserver = NSNotificationCenter.defaultCenter().addObserverForName(AWSMobileClient.AWSMobileClientDidCompleteInitialization, object: AWSMobileClient.sharedInstance, queue: NSOperationQueue.mainQueue(), usingBlock: {[weak self](note: NSNotification) -> Void in
            guard let strongSelf = self else { return }
            print("Initialization of AWSIdentityManager complete, we now have an identityId")
            strongSelf.refreshInterface("-Complete")
            })`

I did report this to the feedback page on the mobile-hub. It doesn't impact the demo app because the demo app does not try to USE an identityId until the user chooses something from the Main View Controller.

There is a complete example app at [https://github.com/BruceBuckland/SignIn-awsmhh](https://github.com/BruceBuckland/SignIn-awsmhh)

**Comment by BruceBuckland** [comment]
@digitalpho3nix 
Possible cause:  AWSMobile client has a bug (or missing feature) with respect to the resumption of existing sessions.  If you (in your viewDidLoad for example) try to use an identityId upon startup you will get a crash.  That is because AWSIdentityManager defaultIdentityManager] resumeSessionWithCompletionHandler takes a while to finish resuming the sessions (it has to hit an AWS service through the web) but it returns immediately with true (or YES for Obj-c) and the appDelegate kicks off the ViewController.

What I did was to modify AWSMobileClient.swift to do the following:

`        if (!isInitialized) {
            AWSIdentityManager.defaultIdentityManager().resumeSessionWithCompletionHandler({(result: AnyObject?, error: NSError?) -> Void in
                print("Result: \(result) \n Error:\(error)")
                NSNotificationCenter.defaultCenter().postNotificationName(AWSMobileClient.AWSMobileClientDidCompleteInitialization, object: self, userInfo: nil)
            })
            isInitialized = true
        }`

and then defined that notification just after the class

`  // Constants 
    static let AWSMobileClientDidCompleteInitialization = "com.amazonaws.AWSMobileClient.AWSMobileClientDidCompleteInitialization"`

then in your viewController (or somewhere else) set up a target for the notification. I did the following in my MainViewController.swift 

`// when we really have an identityId - start processing.
        completeInitializationObserver = NSNotificationCenter.defaultCenter().addObserverForName(AWSMobileClient.AWSMobileClientDidCompleteInitialization, object: AWSMobileClient.sharedInstance, queue: NSOperationQueue.mainQueue(), usingBlock: {[weak self](note: NSNotification) -> Void in
            guard let strongSelf = self else { return }
            print("Initialization of AWSIdentityManager complete, we now have an identityId")
            strongSelf.refreshInterface("-Complete")
            })`

I did report this to the feedback page on the mobile-hub. It doesn't impact the demo app because the demo app does not try to USE an identityId until the user chooses something from the Main View Controller.

There is a complete example app at [https://github.com/BruceBuckland/SignIn-awsmhh](https://github.com/BruceBuckland/SignIn-awsmhh)

**Comment by digitalpho3nix** [comment]
@BruceBuckland fantastic workaround, thanks for your time :)
