### ISSUE TITLE
onLogin called twice when app starts

### ISSUE THREAD

**Issue by simonhopkin** [aws/aws-mobilehub-helper-ios#45]
Hi,

I'm seeing the `onLoginWithSignInProvider` call back of `AWSSignInDelegate` called twice when my app starts.

Is this intended behaviour?

I traced it down to the `resumeSessionWithCompletionHandler()` method of `AWSSignInManager`.  This makes a call to `[self.potentialSignInProvider reloadSession]` which in turn results in a call to `completeLogin()`.  However `completeLogin()` is also called within `resumeSessionWithCompletionHandler()`.  It might be clearer if I point it out in the code:

```
- (void)resumeSessionWithCompletionHandler:(void (^)(id result, NSError *error))completionHandler {

    self.completionHandler = completionHandler;
    
    for(NSString *key in [self getRegisteredSignInProviders]) {
        if ([[self signInProviderForKey:key] isLoggedIn]) {
            self.potentialSignInProvider = [self signInProviderForKey:key];
        }
    }
    
    [self.potentialSignInProvider reloadSession];    // Results in a call to completeLogin
    
    if (self.potentialSignInProvider == nil) {
        [self completeLogin];                    // Results in second call to completeLogin
    }
}
```

Is this a bug?

**Comment by kvasukib** [comment]
Thank you @simonhopkin for reporting to us. For Facebook and Cognito User Pools Sign In providers, the `reloadSession` method internally calls `completeLogin` which sets the signInProvider to nil (https://github.com/aws/aws-mobilehub-helper-ios/blob/master/AWSMobileHubHelper/Authentication/AWSSignInManager.m#L138). Now `self.potentialSignInProvider == nil` is true and completeLogin is called again.

We are working on to fix the issue. We will update this thread once the fix is out. Thank you!

**Comment by simonhopkin** [comment]
Hi, do you have any update on a fix for this issue?

**Comment by muellerfr** [comment]
Since the code has moved to the iOS SDK, I create the issue there to track it: 
https://github.com/aws/aws-sdk-ios/issues/1054
